src/AppBundle/Entity/Event.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EventRepository")
 */
class Event
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     * @Assert\Length(
     *     min=50,
     *     max="2500"
     * )
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startTime", type="datetime")
     * @Assert\NotBlank()
     */
    private $startTime;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="endTime", type="datetime")
     * @Assert\NotBlank()
     */
    private $endTime;

    /**
     * @var string
     *
     * @ORM\Column(name="picture", type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @var string
     *
     * @ORM\Column(name="latitude", type="string", length=255, nullable=true)
     */
    private $latitude;

    /**
     * @var string
     *
     * @ORM\Column(name="longitude", type="string", length=255, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Association", inversedBy="events")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     * @Assert\NotNull()
     */
    private $association;
    
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Place", inversedBy="events")
     * @ORM\JoinColumn(nullable=true, onDelete="CASCADE")
     */
    private $placeEntity;

    /**
     * @var string
     *
     * @ORM\Column(name="website", type="string", length=255, nullable=true)
     */
    private $website;
    
    /**
     * @var string
     *
     * @ORM\Column(name="websiteTitle", type="string", length=255, nullable=true)
     */
    private $websiteTitle;
    
    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     */
    private $email;
    
    /**
     * @var string
     *
     * @ORM\Column(name="carpool", type="string", length=255, nullable=true)
     */
    private $carpool;

    /**
     * @var boolean
     *
     * @ORM\Column(name="searchVolunteers", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $searchVolunteers = false;

    /**
     * @var boolean
     *
     * @ORM\Column(name="published", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $published = true;

    /**
     * @var boolean
     *
     * @ORM\Column(name="free", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $free = true;

    /**
     * @var boolean
     *
     * @ORM\Column(name="pricing", type="string", length=255, nullable=true)
     */
    private $pricing;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="string", length=1, nullable=false)
     */
    private $status;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creationDate", type="datetime", nullable=true)
     */
    private $creationDate;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updateDate", type="datetime", nullable=true)
     */
    private $updateDate;
    
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Document",mappedBy="event")
     * @ORM\OrderBy({"name": "asc"})
     */
    private $documents;

    private $file;
    
    const STATUS_CANCELED = "C";
    const STATUS_POSTPONED = "P";
    const STATUS_SCHEDULED = "S";
    
    
    public function __construct() {
        
        $this->setCreationDate(new \DateTime());
        $this->setStatus(Event::STATUS_SCHEDULED);
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Event
     */
    public function setName($name)
    {
        $this->name = $name;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    public function getNameForUrl()
    {
        $name = "action";

        if (!empty($this->getName())) {
            $name = strtolower(trim($this->getName()));
            
            $name = str_replace("’", "-", $name);
            $name = str_replace("'", "-", $name);
            $name = str_replace('"', "", $name);
            $name = str_replace("/", "", $name);
            $name = str_replace("|", "", $name);
            $name = str_replace('\\', "", $name);
            $name = str_replace('?', "", $name);
            $name = str_replace('!', "", $name);
            $name = str_replace('(', "", $name);
            $name = str_replace(')', "", $name);
            $name = str_replace('{', "", $name);
            $name = str_replace('}', "", $name);
            $name = str_replace('[', "", $name);
            $name = str_replace(']', "", $name);
            $name = str_replace('°', "", $name);
            $name = str_replace('&', "", $name);
            $name = str_replace('§', "", $name);
            $name = str_replace('*', "", $name);
            $name = str_replace('%', "", $name);
            $name = str_replace(':', "", $name);
            $name = str_replace(',', "", $name);
            $name = str_replace(';', "", $name);
            $name = str_replace('=', "", $name);
            $name = str_replace('+', "", $name);
            $name = str_replace('.', "", $name);
            $name = str_replace('<', "", $name);
            $name = str_replace('>', "", $name);
            $name = str_replace('@', "", $name);
            $name = str_replace('#', "", $name);
            
            $name = trim($name);
            $name = str_replace(" ", "-", $name);
            
            $name = str_replace("é", "e", $name);
            $name = str_replace("è", "e", $name);
            $name = str_replace("ê", "e", $name);
            $name = str_replace("ë", "e", $name);
            $name = str_replace("â", "a", $name);
            $name = str_replace("à", "a", $name);
            $name = str_replace("ä", "a", $name);
            $name = str_replace("ô", "o", $name);
            $name = str_replace("ö", "o", $name);
            $name = str_replace("ù", "u", $name);
            $name = str_replace("ü", "u", $name);
            $name = str_replace("û", "u", $name);
            $name = str_replace("î", "i", $name);
            $name = str_replace("ï", "i", $name);
            $name = str_replace("ç", "c", $name);
            $name = str_replace("æ", "ae", $name);
            $name = str_replace("œ", "oe", $name);
            
            // Uppercase
            $name = str_replace("É", "e", $name);
            $name = str_replace("È", "e", $name);
            $name = str_replace("Ê", "e", $name);
            $name = str_replace("Ë", "e", $name);
            $name = str_replace("Â", "a", $name);
            $name = str_replace("À", "a", $name);
            $name = str_replace("Ä", "a", $name);
            $name = str_replace("Ô", "o", $name);
            $name = str_replace("Ö", "o", $name);
            $name = str_replace("Ù", "u", $name);
            $name = str_replace("Ü", "u", $name);
            $name = str_replace("Î", "i", $name);
            $name = str_replace("Ï", "i", $name);
            $name = str_replace("Ç", "c", $name);
            $name = str_replace("Æ", "ae", $name);
            $name = str_replace("Œ", "oe", $name);
            
            while(strpos($name, "--") !== false) {
            	
            	$name = str_replace("--", "-", $name);
            }
        }

        return $name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Event
     */
    public function setDescription($description)
    {
        $this->description = $description;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set startTime
     *
     * @param \DateTime $startTime
     *
     * @return Event
     */
    public function setStartTime($startTime)
    {
        $this->startTime = $startTime;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get startTime
     *
     * @return \DateTime
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Set endTime
     *
     * @param \DateTime $endTime
     *
     * @return Event
     */
    public function setEndTime($endTime)
    {
        $this->endTime = $endTime;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get endTime
     *
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * Set picture
     *
     * @param string $picture
     *
     * @return Event
     */
    public function setPicture($picture)
    {
        $this->picture = $picture;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get picture
     *
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
        

src/AppBundle/Entity/Place.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Place
 *
 * @ORM\Table(name="place")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PlaceRepository")
 */
class Place
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="street", type="string", length=255, nullable=true)
     */
    private $street;
    
    /**
     * @var string
     *
     * @ORM\Column(name="street2", type="string", length=255, nullable=true)
     */
    private $street2;

    /**
     * @var string
     *
     * @ORM\Column(name="zipCode", type="string", length=255, nullable=true)
     */
    private $zipCode;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="latitude", type="string", length=255)
     */
    private $latitude;

    /**
     * @var string
     *
     * @ORM\Column(name="longitude", type="string", length=255)
     */
    private $longitude;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="deleted", type="boolean", nullable=false)
     */
    private $deleted = false;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="creationDate", type="datetime", nullable=true)
     */
    private $creationDate;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updateDate", type="datetime", nullable=true)
     */
    private $updateDate;
    
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Event",mappedBy="placeEntity")
     */
    private $events;
    
    
    public function __construct() {
        
        $this->setCreationDate(new \DateTime());
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Place
     */
    public function setName($name)
    {
        $this->name = $name;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set street
     *
     * @param string $street
     *
     * @return Place
     */
    public function setStreet($street)
    {
        $this->street = $street;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get street
     *
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }
    
    /**
     * Set street2
     *
     * @param string $street2
     *
     * @return Place
     */
    public function setStreet2($street2)
    {
        $this->street2 = $street2;
        
        $this->setUpdateDate(new \DateTime());
        
        return $this;
    }
    
    /**
     * Get street2
     *
     * @return string
     */
    public function getStreet2()
    {
        return $this->street2;
    }

    /**
     * Set zipCode
     *
     * @param string $zipCode
     *
     * @return Place
     */
    public function setZipCode($zipCode)
    {
        $this->zipCode = $zipCode;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get zipCode
     *
     * @return string
     */
    public function getZipCode()
    {
        return $this->zipCode;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return Place
     */
    public function setCity($city)
    {
        $this->city = $city;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set latitude
     *
     * @param string $latitude
     *
     * @return Place
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get latitude
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set longitude
     *
     * @param string $longitude
     *
     * @return Place
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;
        
        $this->setUpdateDate(new \DateTime());

        return $this;
    }

    /**
     * Get longitude
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }
    
    public function isDeleted()
    {
        return $this->deleted;
    }
    
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;
        
        $this->setUpdateDate(new \DateTime());
    }
    
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;
        
        return $this;
    }
    
    public function getCreationDate()
    {
        return $this->creationDate;
    }
    
    public function setUpdateDate($updateDate)
    {
        $this->updateDate = $updateDate;
        
        return $this;
    }
    
    public function getUpdateDate()
    {
        return $this->updateDate;
    }
    
    public function getEvents()
    {
        return $this->events;
    }
    
    public function getFullAddress()
    {
        $address = "";
        
        if(!empty($this->getStreet()) || !empty($this->getStreet2())) {
            
            if(!empty($this->getStreet())) {
                $address = $this->getStreet();
            }
            
            if(!empty($this->getStreet2())) {
                
                if(!empty($this->getStreet())) {
                    $address .= " - ";
                }
                
                $address .= $this->getStreet2();
            }
            
            if (!empty($this->getZipCode()))
                $address .= ", " . $this->getZipCode();
        }
        
        if (!empty($this->getCity())) {
            
            if(!empty($address)) {
                if(!empty($this->getZipCode()))
                    $address .= " ";
                else
                    $address .= ", ";
            }
            
            $address .= $this->getCity();
        }
        
        return $address;
    }
}

src/AppBundle/Resources/views/Default/event.html.twig
{% extends 'AppBundle:Design:design.html.twig' %}

{% block title %}
	{% if event is null %}
		{{ "event_unknown"|trans }}
	{% else %}
		{{ event.name }}
	{% endif %}
	 - {{ parent() }}
{% endblock %}

{% block content %}
    <div class="container">
        {# TODO #}
        {% if app.request.query.has("source") %}
            {% if app.request.query.get("source") == "admin_events" %}
                <p>
                    <a class="btn btn-light" href="{{ url("app_admin_events") }}"><span aria-hidden="true">&larr;</span> {{ "come_back_to_admin_page"|trans({}, "messages") }}</a>
                </p>
            {% elseif app.request.query.get("source") == "super_admin_events" %}
                <p>
                    <a class="btn btn-light" href="{{ url("app_superadmin_events") }}"><span aria-hidden="true">&larr;</span> {{ "come_back_to_admin_page"|trans({}, "messages") }}</a>
                </p>
            {% endif %}
        {% endif %}

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url("app_index") }}">{{ "homepage"|trans }}</a></li>

                {% if event is not null and app.request.query.get("source") == "association" %}
                    {% if event.association.isWorkshop %}
                        <li class="breadcrumb-item"><a href="{{ url("app_workshop", {"id": event.association.id, "name": event.association.nameForUrl}) }}">{{ event.association.name }}</a></li>
                    {% else %}
                        <li class="breadcrumb-item"><a href="{{ url("app_association", {"id": event.association.id, "name": event.association.nameForUrl}) }}">{{ event.association.name }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="breadcrumb-item"><a href="{{ url("app_events") }}">{{ "the_events"|trans }}</a></li>
                {% endif %}
                <li class="breadcrumb-item active" aria-current="page">
                    {% if event is null %}
                        {{ "event_unknown"|trans }}
                    {% else %}
                        {{ event.name }}
                    {% endif %}
                </li>
            </ol>
        </nav>

        {% if event is null %}
            <h1>{{ "event_unknown"|trans }}</h1>
        {% else %}
        
    		<p class="center">
    	        {% if event.picture is not empty %}
                	<a href="{{ asset(event.picturePath) }}">
                		<img src="{{ asset(event.picturePath) }}" class="fit picture-element"/>
            		</a>
            	{% elseif event.association.picture is not empty %}
            		<a href="{{ asset(event.association.picturePath) }}">
                		<img src="{{ asset(event.association.picturePath) }}" class="fit picture-element"/>
                	</a>
                {% endif %}
                <h3 class="center">{{ event.name }}</h3>
            </p>
            
            {% if event.isCanceled %}
            	<div class="alert alert-info" role="alert">{{ "event_canceled"|trans }}</div>
            {% elseif event.isPostponed %}
            	<div class="alert alert-info" role="alert">{{ "event_postponed"|trans }}</div>
            {% endif %}
            
            {% if event.searchVolunteers %}
            	<div class="alert alert-success" role="alert">
                    <svg width="1em" height="1em"
                         viewBox="0 0 16 16" class="bi bi-flag-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M3.5 1a.5.5 0 0 1 .5.5v13a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5z"/>
                        <path fill-rule="evenodd" d="M3.762 2.558C4.735 1.909 5.348 1.5 6.5 1.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126a8.89 8.89 0 0 0 .593-.25c.058-.027.117-.053.18-.08.57-.255 1.278-.544 2.14-.544a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5c-.638 0-1.18.21-1.734.457l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 9.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916A.5.5 0 0 1 3.5 9V3a.5.5 0 0 1 .223-.416l.04-.026z"/>
                    </svg> {{ "search_volunteers_message"|trans }}
                </div>
            {% endif %}
            
            <p>{{ "proposed_by"|trans }} <a href="{% if event.association.isWorkshop %}{{ url("app_workshop", {"id": event.association.id, "name": event.association.nameForUrl}) }}{% else %}{{ url("app_association", {"id": event.association.id, "name": event.association.nameForUrl}) }}{% endif %}">{{ event.association.name }}</a></p>
    
            <p style="font-family: 'Roboto Light', 'Roboto Regular', serif; font-size: 1.1em; margin-top: 20px; max-width: 1000px;">{{ event.description|nl2br }}</p>
    		
            {% if event.website is not empty or event.email is not empty %}
                <p style="margin-bottom: 20px;">
                
                	{% if event.website is not empty %}
                		<a href="{{ event.website }}">{% if event.websiteTitle is not empty %}{{ event.websiteTitle }}{% else %}{{ "read_more"|trans }}{% endif %}</a>
            		
                		{% if event.email is not empty %}<br/>{% endif %}
                	{% endif %}
            		
            		{% if event.email is not empty %}
            			
                    	{% set emailSplitted = event.email|split("@") %}
                    	
                    	{% if emailSplitted|length != 2 %}
                            {{ "email_colon"|trans({"%email%": event.email }) }}
                    	{% else %}
                        	<span>
                            {{ "email_colon"|trans({"%email%": emailSplitted[0] }) }} <img src="{{ asset("bundles/app/img/at_sign.png") }}"/> {{ emailSplitted[1] }}
                            </span>
                        {% endif %}
                    {% endif %}
        		</p>
            {% endif %}
            
            {% if event.documents|length > 0 %}
            	<p>
            		{% for document in event.documents %}
        				<a href="{{ asset(document.path) }}">{{ document.name }}</a><br/>
            		{% endfor %}
            	</p>
            {% endif %}
    
            <h4>{{ "when"|trans }}</h4>
            <p>
            	{{ event.startTime|localizeddate("full", "short", locale, time_zone) }} -
                {% if event.takesLessThanOneDay %}
                    {{ event.endTime|localizeddate("none", "short", locale, time_zone) }}
                {% else %}
                    {{ event.endTime|localizeddate("full", "short", locale, time_zone) }}
                {% endif %}
                <a href="{{ url("app_event_ics", {"id": event.id}) }}" title="{{ "add_to_calendar"|trans }}" type="button" class="btn btn-dark btn-sm">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar-event-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v1h16V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5zM0 5h16v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5zm12.5 2a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                    </svg>
                </a>
            </p>
            
            <h4>{{ "pricing"|trans }}</h4>
            <p>
                {% if event.free %}
                	{{ "free"|trans }}
                {% else %}
                	<strong>{{ "paying"|trans }}</strong>
                	<br/>
                    {{ event.pricing }}
                {% endif %}
    		</p>
    		
    		{% if event.placeEntity is not null %}
                <h4>{{ "where"|trans }}</h4>
                
                {% set now = "now"|date("Y-m-d H:i:s") %}
                
                {% if event.carpool is not empty and event.endTime|date("Y-m-d H:i:s") > now %}
                	<div class="alert alert-success" role="alert">{{ "carpool_available"|trans }}</div>
                {% endif %}
                
                <p>
                    {% if event.carpool is not empty and event.endTime|date("Y-m-d H:i:s") > now %}
                    	
                    	<table>
                    		<tr>
                    			<td>
                    				<a type="button" class="btn btn-success" href="{{ event.carpool }}" target="_blank">{{ "carpool"|trans }}</a>
                    			</td>
                    			<td style="padding-left: 1rem;">
                    				<strong>{{ event.placeEntity.name }}</strong>
            						
                                    {% if event.placeEntity.fullAddress is not empty %}
                                    	<br/>
                                        {{ event.placeEntity.fullAddress }}
                                    {% endif %}
                    			</td>
                    		</tr>
                    	</table>
                    {% else %}
        				<strong>{{ event.placeEntity.name }}</strong>
            
                        {% if event.placeEntity.fullAddress is not empty %}
                        	<br/>
                            {{ event.placeEntity.fullAddress }}
                        {% endif %}
                    {% endif %}
                </p>
            {% endif %}
        {% endif %}
    </div>
    {% if event is not null and event.placeEntity is not null %}
    	<!--<div id="mapid" class="map" style=""></div>-->
    {% endif %}
{% endblock %}

{% block js %}
    <script type="application/javascript">

{#    	{% if event is not null and event.placeEntity is not null %}#}
{#            var map = L.map('mapid').setView([{{ event.placeEntity.latitude }}, {{ event.placeEntity.longitude }}], 15);#}
{#    #}
{#            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={{ mapbox_access_token }}', {#}
{#                maxZoom: 18,#}
{#                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +#}
{#                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +#}
{#                'Imagery © <a href="http://mapbox.com">Mapbox</a>',#}
{#                id: 'mapbox.streets'#}
{#            }).addTo(map);#}
{#    #}
{#            // Prevent the zoom when we scroll the webpage#}
{#            map.scrollWheelZoom.disable();#}
{#    #}
{#            var marker = L.marker([{{ event.placeEntity.latitude }}, {{ event.placeEntity.longitude }}]).addTo(map);#}
{#            marker.bindPopup('<strong>{{ event.placeEntity.name }}</strong>'+#}
{#                    '<br/><strong>{{ event.startTime|localizeddate("full", "short", locale, time_zone) }}</strong>'+#}
{#                    '{% if event.placeEntity.street is not empty %}<br/>{{ event.placeEntity.street }}{% endif %}'+#}
{#                    '{% if event.placeEntity.street2 is not empty %}<br/>{{ event.placeEntity.street2 }}{% endif %}'+#}
{#                    '{% if event.placeEntity.zipCode is not empty %}<br/>{{ event.placeEntity.zipCode }}{% if event.placeEntity.city is not empty %} {{ event.placeEntity.city }}{% endif %}{% endif %}'+#}
{#                    '{% if event.placeEntity.zipCode is empty and event.placeEntity.city is not empty %}<br/>{{ event.placeEntity.city }}{% endif %}'#}
{#            );#}
{#            marker.on('mouseover', function (e) {#}
{#                this.openPopup();#}
{#            });#}
{#            marker.on('mouseout', function (e) {#}
{#                this.closePopup();#}
{#            });#}
{#        {% endif %}#}
    </script>
{% endblock %}